# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 02:07
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0003_remove_comment_add_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='enrichment_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('user', 'post')]),
        ),
    ]
